# PostgreSQL configuration

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: soham
  username: soham
  password: soham@123
  host: localhost

test:
  <<: *default
  database: soham_test
  username: soham
  password: soham@123
  host: localhost

production:
  <<: *default
  database: yourapp_production
  username: <%= ENV["PGUSER"] || "postgres" %>
  password: <%= ENV["PGPASSWORD"] || "password" %>
  host: <%= ENV["PGHOST"] || "localhost" %>
